#!/bin/zsh

# Args: $0 {read,write} [--extra_flags]


mn_data_ip='10.10.10.202'
mn_ssh_name='fbss4'
rdma_type=$1
shift

if [[ $rdma_type = 'read' ]]; then 
	port=18515
elif [[ $rdma_type = 'write' ]]; then 
	port=18516
else
	echo "$0 <{read,write}>"
	exit 1
fi
	

setup-network

cmd=(
	timeout 
	3m
	"/home/sslee/ofed-perftest-24.07/ib_${rdma_type}_bw"
	--rdma_cm 
	--mtu 4096 --size 4096 
	--rx-depth 1 
	#--use_old_post_send     # Prefer `ibv_post_send()` to `ib_wr_*()` datapath API. 
	--report_gbits --report-both --noPeak --cpu_util
	--port $port
	--duration 20 
)
echo $cmd

rm -f /tmp/$rdma_type.hwcounter.{pre,post}

ssh $mn_ssh_name -- $cmd $@ &>$rdma_type.server.out &  
server_pid=$! 
sleep 5

$cmd $@ $mn_data_ip &>$rdma_type.client.out 

wait $server_pid
