#!/bin/zsh

mn_data_ip='10.10.10.202'
mn_ssh_name='fbss4'

# todo try --use-hugepages

cmd=(
	timeout 
	3m
	taskset -c 2 
	/home/sslee/ofed-perftest-24.07/ib_read_bw 
	--rdma_cm --mtu 4096 --size 4096 --rx-depth 1 
	--report_gbits --report-both --noPeak --cpu_util
	--duration 20
	--port 18515
#	--iters 500
)

rm -f /tmp/read.hwcounter.{pre,post}

ssh $mn_ssh_name -- $cmd $@ &>read.server.out &  
server_pid=$! 
sleep 5

$cmd $@ $mn_data_ip &>read.client.out 

wait $server_pid
