#!/bin/zsh

mn_data_ip=10.10.1.2
mn_ssh_name='server'

# todo try --use-hugepages

cmd=(
	../ib_write_bw
	--rdma_cm --mtu 4096 --size 4096 --rx-depth 1 
	--report_gbits --report-both --noPeak --cpu_util
	--duration 60
	--port 17575
#	--iters 500
)

rm -f /tmp/write.hwcounter.{pre,post}

ssh $mn_ssh_name -- $cmd $@ &>write.server.out &
server_pid=$!
sleep 1

$cmd $@ $mn_data_ip &>write.client.out 

wait $server_pid
