#!/bin/zsh

dir='class1-deepsweep'
setup-network

mkdir -p $dir

#sudo cpupower frequency-set -g performance
#ssh server -- sudo cpupower frequency-set -g performance

function run () { 
	local qp=$1
	local txdepth=$2
	local postlist=$3

	local schema="qp${qp}-txd${txdepth}-pl${postlist}"

	./remread --qp $qp --tx-depth $txdepth --post_list $postlist
	mv /tmp/read.hwcounter.pre "$dir/hwpre.read.$schema.out"
	mv /tmp/read.hwcounter.post "$dir/hwpost.read.$schema.out"
	mv read.client.out "$dir/client.read.$schema.out"
	mv read.server.out "$dir/server.read.$schema.out"
}


#for txdepth in 2 4 8 16 32 64; do 
for txdepth in 2 8 32; do 
	for qp in 1 2 $(seq 4 4 64); do 
		run $qp $txdepth $txdepth
		sleep 3s
	done
done
