#!/bin/zsh

setup-network

mkdir -p class3

dir='class3'
txdepth=32

for fhqp in 1 16 32 48; do 
	for cnqp in 1 4 8; do 
		local schema="fhqp${fhqp}-cnqp${cnqp}-txd${txdepth}-pl${postlist}"
		./rdma-helper 'read' --qp $fhqp --tx-depth 1 --post_list 1 --use_old_post_send &
		./rdma-helper 'write' --qp $cnqp --tx-depth $txdepth --post_list 1 --use_old_post_send &
		wait

		sleep 3

		for type in read write; do
			mv "/tmp/$type.hwcounter.pre" "$dir/hwpre.$type.$schema.out"
			mv "/tmp/$type.hwcounter.post" "$dir/hwpost.$type.$schema.out"
			mv "$type.client.out" "$dir/client.$type.$schema.out"
			mv "$type.server.out" "$dir/server.$type.$schema.out"
		done
	done
done
