#!/bin/zsh

dir='class1-quicksweep'
setup-network

mkdir -p $dir

function run () { 
	local qp=$1
	local txdepth=$2
	local postlist=$3

	local schema="qp${qp}-txd${txdepth}-pl${postlist}"

	./remread --qp $qp --tx-depth $txdepth --post_list $postlist
	mv /tmp/read.hwcounter.pre "$dir/hwpre.read.$schema.out"
	mv /tmp/read.hwcounter.post "$dir/hwpost.read.$schema.out"
	mv read.client.out "$dir/client.read.$schema.out"
	mv read.server.out "$dir/server.read.$schema.out"
	sleep 3s
}

local txdepth=1
local postlist=1
for qp in 1 2 $(seq 4 4 64); do 
	run $qp $txdepth $postlist
done
